FROM archlinux:latest

# Remove 'NoExtract' directives that prevent installing manpages, among other things
RUN find /etc/pacman.conf /etc/pacman.d -type f -print0 2>/dev/null \
	| xargs -0 sed -i '/NoExtract.*usr\/share\/man/d;/NoExtract.*usr\/share\/help/d;/NoExtract.*usr\/share\/doc/d;/NoExtract.*etc\/pacman.d\/mirrorlist/d'

RUN pacman-key --init && pacman --noconfirm -Syu && pacman -Fy

RUN pacman -S --noconfirm \
	age \
	aria2 \
	asciidoctor \
	base-devel \
	bash-language-server \
	bc \
	blender \
	chafa \
	chezmoi \
	clang \
	cmake \
	dash \
	fd \
	ffmpegthumbnailer \
	fish \
	fzf \
	gcr \
	git \
	git-filter-repo \
	github-cli \
	git-lfs \
	glow \
	go \
	gopls \
	graphicsmagick \
	haskell-language-server \
	highlight \
	imagemagick \
	inetutils \
	jq \
	kakoune \
	kakoune-lsp \
	kguiaddons \
	kwindowsystem \
	less \
	lf \
	libnotify \
	lowdown \
	lsof \
	lua-language-server \
	man-db \
	man-pages \
	marksman \
	mpc \
	mpd \
	mpv \
	mupdf-tools \
	ncmpcpp \
	ncmpcpp \
	nmap \
	npm \
	ols \
	openai-codex \
	openssh \
	pandoc \
	parallel \
	pass \
	pass-otp \
	perl-image-exiftool \
	pigz \
	pyright \
	qt6-base \
	r \
	ramalama \
	renameutils \
	ripgrep \
	ripgrep-all \
	rsync \
	rust-analyzer \
	rustup \
	shellcheck \
	shfmt \
	socat \
	sudo \
	task \
	taskwarrior-tui \
	texlab \
	tig \
	timew \
	tree \
	unzip \
	uv \
	visidata \
	vscode-css-languageserver \
	vscode-html-languageserver \
	vscode-json-languageserver \
	w3m\
	wget \
	which \
	wl-clipboard \
	xorg-xauth \
	zathura \
	zathura-cb \
	zathura-pdf-mupdf \
	zathura-ps \
	zip
	zls \


# `nb`
RUN wget https://raw.github.com/xwmx/nb/master/nb -O /usr/local/bin/nb && \
	chmod +x /usr/local/bin/nb && \
	EDITOR=kak nb completions install --download
RUN npm install -g mozilla-readability-cli @andymatuschak/note-link-janitor

# Lzip suite
WORKDIR /build
RUN wget https://download.savannah.nongnu.org/releases/lzip/lzip-1.26.tar.gz \
	&& tar -xf lzip-*.tar.gz \
	&& cd lzip-1.26 \
	&& ./configure \
	&& make -j"$(nproc)" check \
	&& make install
RUN wget https://download.savannah.nongnu.org/releases/lzip/lzlib/lzlib-1.16.tar.lz \
	&& tar -xf lzlib-*.tar.lz \
	&& cd lzlib-1.16 \
	&& ./configure \
	&& make -j"$(nproc)" check \
	&& make install
RUN wget https://download.savannah.nongnu.org/releases/lzip/plzip/plzip-1.13.tar.lz \
	&& tar -xf plzip-*.tar.lz \
	&& cd plzip-1.13 \
	&& ./configure \
	&& make -j"$(nproc)" check \
	&& make install
RUN wget https://download.savannah.nongnu.org/releases/lzip/tarlz/tarlz-0.29.tar.lz \
	&& tar -xf tarlz-*.tar.lz \
	&& cd tarlz-0.29 \
	&& ./configure \
	&& make -j"$(nproc)" check \
	&& make install
RUN wget https://download.savannah.nongnu.org/releases/lzip/lziprecover/lziprecover-1.26.tar.lz \
	&& tar -xf lziprecover-*.tar.lz \
	&& cd lziprecover-1.26 \
	&& ./configure \
	&& make -j"$(nproc)" check \
	&& make install


RUN useradd -m -G wheel -s /usr/bin/fish tom
WORKDIR /home/tom
RUN rm -rf /build
RUN printf '%%wheel ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/99_tom
USER tom

RUN rustup default stable

RUN git clone https://aur.archlinux.org/yay.git \
	&& cd yay \
	&& makepkg -sir --noconfirm \
	&& cd .. \
	&& rm -rf yay

RUN yay -S --noconfirm \
	tidy-viewer \
	cmake-language-server \
	crystalline-bin \
	clojure-lsp-bin

RUN sudo mandb -c

