FROM archlinux:latest

# Remove 'NoExtract' directives that prevent installing manpages, among other things
RUN find /etc/pacman.conf /etc/pacman.d -type f -print0 2>/dev/null \
	| xargs -0 sed -i '/NoExtract.*usr\/share\/man/d;/NoExtract.*usr\/share\/help/d;/NoExtract.*usr\/share\/doc/d;/NoExtract.*etc\/pacman.d\/mirrorlist/d'

RUN pacman-key --init && pacman --noconfirm -Syu && pacman -Fy

RUN pacman -S --noconfirm \
	age \
	aria2 \
	base-devel \
	bc \
	chafa \
	chezmoi \
	cmake \
	dash \
	fd \
	ffmpegthumbnailer \
	fish \
	fzf \
	git \
	git-filter-repo \
	github-cli \
	git-lfs \
	glow \
	gopass \
	gopls \
	highlight \
	imagemagick \
	imv \
	inetutils \
	jq \
	kakoune \
	kakoune-lsp \
	kguiaddons \
	kwindowsystem \
	less \
	lf \
	libnotify \
	lsof \
	man-db \
	man-pages \
	mpc \
	mpd \
	mpv \
	mupdf-tools \
	ncmpcpp \
	ncmpcpp \
	openssh \
	perl-image-exiftool \
	pigz \
	pyright \
	qt6-base \
	ramalama \
	ripgrep \
	rsync \
	shellcheck \
	shfmt \
	sudo \
	tree \
	unzip \
	wget \
	which \
	wl-clipboard \
	xorg-xauth \
	zathura \
	zathura-cb \
	zathura-pdf-mupdf \
	zathura-ps \
	zip

RUN mandb -cp

RUN useradd -m -G wheel -s /usr/bin/fish tom

RUN printf '%%wheel ALL=(ALL:ALL) NOPASSWD: ALL' > /etc/sudoers.d/99_tom

USER tom

WORKDIR /home/tom

RUN git clone https://aur.archlinux.org/yay.git \
	&& cd yay \
	&& makepkg -sir --noconfirm \
	&& cd .. \
	&& rm -rf yay

RUN yay -S --noconfirm \
	crush \
	openai-codex-bin


