autoload -U colors

HISTFILE=$XDG_DATA_HOME/zsh_history
HISTSIZE=100000
SAVEHIST=100000

setopt extendedglob
unsetopt beep
bindkey -v
bindkey '^R' history-incremental-search-backward

autoload -Uz compinit; compinit
autoload -Uz promptinit; promptinit

# Enable completion cache
zstyle ':completion::complete:*' use-cache 1

#zstyle ':completion:*' menu select
#zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

# Load prompt
PROMPT=$'%F{white}%~ %B%F{blue}>%f%b '

# Extra prompts
#source $ZDOTDIR/prompts
#source $ZDOTDIR/purification
#source $ZDOTDIR/git-prompt.zsh
#ZSH_GIT_PROMPT_FORCE_BLANK=1
#ZSH_THEME_GIT_PROMPT_PREFIX="%B · %b"
#ZSH_THEME_GIT_PROMPT_SUFFIX="›"
#ZSH_THEME_GIT_PROMPT_SEPARATOR=" ‹"
#ZSH_THEME_GIT_PROMPT_BRANCH="λ%{$fg_bold[cyan]%}"
#ZSH_THEME_GIT_PROMPT_DETACHED="%{$fg_no_bold[cyan]%}:"
#ZSH_THEME_GIT_PROMPT_BEHIND="%{$fg_no_bold[cyan]%}↓"
#ZSH_THEME_GIT_PROMPT_AHEAD="%{$fg_no_bold[cyan]%}↑"
#ZSH_THEME_GIT_PROMPT_UNMERGED="%{$fg[red]%}✖"
#ZSH_THEME_GIT_PROMPT_STAGED="%{$fg[green]%}●"
#ZSH_THEME_GIT_PROMPT_UNSTAGED="%{$fg[red]%}✚"
#ZSH_THEME_GIT_PROMPT_UNTRACKED="…"
#ZSH_THEME_GIT_PROMPT_STASHED="%{$fg[blue]%}⚑"
#ZSH_THEME_GIT_PROMPT_CLEAN="%{$fg_bold[green]%}✔"
#PROMPT=$'┏╸%(?..%F{red}%?%f · )%B%~%b$(gitprompt)\n┗╸%F{blue}❯%f%F{cyan}❯%f%F{green}❯%f '

# dtask
#source <(dstask zsh-completion)
#alias task=dstask

#alias ls="eza"
alias ls="ls -h --color=auto --group-directories-first"
alias tree="tree -C"
alias cp="cp -iv"
alias rm="rm -Iv"
alias mv="mv -iv"
alias mkdir="mkdir -pv"
alias shred="shred -un 5"
alias nvbm="nvim $XDG_DATA_HOME/bookmarks"
alias less="less -R"
alias zathura="zathura --fork"

# Void linux
#alias xq="xbps-query -Rs"

eval "$(zoxide init zsh)"

# Add syntax highlighting - must be last line in the file
#source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
