#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#toggle_theme & thmpid=$!

mpd
remaps
shst &
dunst &
mpdris2-rs &
#notify.sh &

#[ -n "$thmpid" ] && wait "$thmpid"
