#!/bin/sh

[ "${TERM}" = "xterm-kitty" ] && exec kitten icat --clear --stdin no --transfer-mode memory </dev/null >/dev/tty
[ -p "${FIFO_UEBERZUG}" ] && printf '{"action":"remove","identifier":"preview"}\n' >"${FIFO_UEBERZUG}"
