{{ if eq .colors "light" -}}
colorscheme catppuccin_latte
{{ else }}
colorscheme catppuccin_mocha
{{- end }}
# Lines numbers and relative numbers
add-highlighter global/ number-lines -relative

# Highlight matching pair
add-highlighter global/ show-matching

# Wrap on word boundaries
add-highlighter global/ wrap -indent -word

# Highlight trailing whitespace
add-highlighter global/ regex \h+$ 0:Error

set-option global scrolloff 5,5

# System clipboard bindings
map global user y "<a-|>clipboard_get.sh<ret>" -docstring "[Y]ank to system clipboard"
map global user p "|clipboard_put.sh<ret>" -docstring "[P]ut from system clipboard"

### A note on the /dev/null black magic ###
# %sh is synchronous by design. It will wait for:
# 1. The shell process to exit.
# 2. All pipes (stdin, stdout, stderr) to close.
#
# The final `&` forks the process, satisfying the first condition, but all
# pipes are left open. So, we need to "close" them:
# - `> /dev/null` to close stdout
# - `2>&1` redirects stderr to stdout, which in this case is `/dev/null` - closed
# - `< /dev/null` closes stdin
# Now, as far as kakoune is concerned, the process has finished and all pipes
# are closed, so control immediately returns to the client.
define-command -docstring "Compile the current document" compile %{
    nop %sh{ {
        compiler $"{kak_buffile}"
    } > /dev/null 2>&1 < /dev/null & }
}
map global user c -docstring "[C]ompile the current file" ":compile<ret>"

map global user = -docstring "Format current buffer with :format" ":format<ret>"

# fzf file chooser
define-command fzf_file %{
    nop %sh{
        foot -T "foot_tmp" sh -c '
		next=$(fzf --height=100% --layout=default --preview "highlight -O ansi --line-range=0-100 {}")
		printf "eval -client %s %%{ edit %s }\n" "$kak_client" "$next" |
		kak -p "$kak_session"
        ' > /dev/null 2>&1 < /dev/null &
    }
}
map global user f -docstring "Browse [f]iles with fzf" ":fzf_file<ret>"

# fzf buffer chooser
define-command fzf_buffer %{
    nop %sh{
        # Create a temporary file for storage
        foot -T "foot_tmp" -e sh -c '
		next=$(printf "%s\n" "$kak_buflist" | tr " " "\n" |
		fzf --height=100% --layout=default --preview "highlight -O ansi --line-range=0-100 {}")
		printf "eval -client %s %%{ buffer %s }\n" "$kak_client" "$next" |
		kak -p "$kak_session"
    ' > /dev/null 2>&1 < /dev/null &
    }
}
map global user b -docstring "Browse [b]uffers with fzf" ":fzf_buffer<ret>"

# Filetypes
hook global BufCreate .*\.[Rr]md %{ set-option buffer filetype markdown }
hook global BufCreate .*\.?Containerfile %{ set-option buffer filetype dockerfile }

# Filetypes with two-space indentation
hook global BufCreate .*\.(js|html|ts|tsx|hs|yml)$ %{
    # Map tab key to `>` in normal mode -- inserts <indentwidth> spaces
    map global insert <tab> '<a-;><a-gt>'
    set-option buffer indentwidth 2
}
# Filetypes with four-space indentation
hook global BufCreate .*\.(py|json|jsonc)$ %{
    map global insert <tab> '<a-;><a-gt>'
    set-option buffer indentwidth 4
}

