#!/usr/bin/env sh

# Description: Fuzzy search from the current directory and `cd` to selection.
# Dependencies: fzf, fd
#
# Details: This is a stripped-down version of the official(?) `fzcd` command.
#          I removed the multi-file options and switched to forcing `fd`
#          as the finder.
# Shell: POSIX compliant
# Author: Anna Arad, Arun Prakash Jana, KlzXS, Thomas Wells
#
# shellcheck disable=SC1090,SC1091
. "$(dirname "$0")"/.nnn-plugin-helper

CTX=+

sel="$(fd -u -t d | fzf --reverse --header="Jump to location")"

if [ -n "$sel" ]; then
    if [ "$sel" = "." ] || { ! [ -d "$sel" ] && ! [ -f "$sel" ]; }; then
        exit 0
    fi

    # Check if the selected path returned by fzf command is absolute
    case $sel in
    /*) nnn_cd "$sel" "$CTX" ;;
    *)
        # Remove "./" prefix if it exists
        sel="${sel#./}"

        if [ "$PWD" = "/" ]; then
            nnn_cd "/$sel" "$CTX"
        else
            nnn_cd "$PWD/$sel" "$CTX"
        fi;;
    esac
fi
