alias ls "ls -h --color auto --group-directories-first"
alias tree "tree -C"
alias cp "cp -iv"
alias rm "rm -Iv"
alias mv "mv -iv"
alias mkdir "mkdir -pv"
alias nvbm "nvim $XDG_DATA_HOME/bookmarks"
alias less "less -R"
alias zathura "zathura --fork"
alias lf "lfcd"
