[gcloud-manager]
home=/var/home/tom/distros/gcloud-home
init=false
start_now=true
nvidia=false
pull=false
root=false
replace=true
pre_init_hooks=sh /var/home/tom/.local/bin/gcloud-fedora.sh
additional_packages="libxcrypt-compat.x86_64 google-cloud-cli"
additional_packages="google-cloud-cli-gke-gcloud-auth-plugin google-cloud-cli-cloud-run-proxy kubectl"
additional_packages="fd ripgrep fzf kakoune jq"
#volume="/tmp/test:/run/a /tmp/test:/run/b"
